### PR TITLE
Fix dependency installation problem

### PR DESCRIPTION
**Pull request by Doodle1106**
This repo requires "plan_utils" to be installed as well.

### CODE REVIEW

**Comment by hlx1996** [comment]
Could you please tell me that which part of this repo requires "plan_utils"?

**Comment by Doodle1106** [comment]
I was following the steps described in README.md and during building I came across compiler errors complaining missing "Goal3DTool". I then built plan_utils and solved the problem. I will try to reproduce it in another machine and I will post a complete log regarding it.

**Comment by Doodle1106** [comment]
Correction: it was not a compiling error but launching error.

Whiling launching cow_and_lady.launch, I came across following error:

`[ERROR] [1566814278.676758193]: PluginlibFactory: The plugin for class 'rviz_plugins/Goal3DTool' failed to load.  Error: According to the loaded plugin descriptions the class rviz_plugins/Goal3DTool with base class type rviz::Tool does not exist. Declared types are  rviz/FocusCamera rviz/Interact rviz/Measure rviz/MoveCamera rviz/PublishPoint rviz/Select rviz/SetGoal rviz/SetInitialPose rviz_plugin_tutorials/PlantFlag
`
To be more specific, this message is needed by:

`src/Fiesta/demo.rviz:    - Class: rviz_plugins/Goal3DTool`

And I solved it by building the aforementioned lib.

**Comment by USTfgaoaa** [comment]
@Doodle1106 
I think it's just because we provide a wrong config file of Rviz. Since in our testing environments, we always have this plugin installed properly.

@hlx1996 You'd better delete this function if Rviz which loads this plugin, and re-upload the rviz.config file again.

**Comment by USTfgaoaa** [comment]
@Doodle1106 BTW, adding the dependency of 'plan_utils' will make this repo complicated, I'd suggest not to do this.

**Comment by hlx1996** [comment]
@Doodle1106, I have modified the config file of rviz, could you please have a try and check if it is bug-free now?

**Comment by Doodle1106** [comment]
Tested on a new machine, all good, thanks for the work!

**Pull request closed without merging**
